#*****************************************************************************************
# Vivado (TM) v2022.2.2 (64-bit)
#
# hicce_w_header.tcl: Tcl script for re-creating project 'hicce_w_header'
#
# Generated by Vivado on Mon Jun 05 11:44:48 CEST 2023
# IP Build 3783773 on Tue Feb 21 23:41:56 MST 2023
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (hicce_w_header.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "/home/kbogt/my_gits/HICCE/hicce-project/hicce_w_header/hicce_w_header.srcs/utils_1/imports/synth_1/HICCEv2_w_header_wrapper.dcp"
#
# 3. The following remote source files that were added to the original project:-
#
#    "/home/kbogt/my_gits/HICCE/hicce-project/VHDL/Sync_count.vhd"
#    "/home/kbogt/my_gits/HICCE/hicce-project/VHDL/ad7982_cnv.vhd"
#    "/home/kbogt/my_gits/HICCE/hicce-project/VHDL/HiCCE_source/intan_RHA_ADC_v1.vhd"
#    "/home/kbogt/my_gits/HICCE/hicce-project/VHDL/spi_master.vhd"
#    "/home/kbogt/my_gits/HICCE/hicce-project/VHDL/HiCCE_source/HiCCEv2_v2022.vhd"
#    "/home/kbogt/my_gits/HICCE/hicce-project/VHDL/counter64.vhd"
#    "/home/kbogt/my_gits/HICCE/hicce-project/VHDL/Timestamp.vhd"
#    "/home/kbogt/my_gits/HICCE/hicce-project/VHDL/Trace_storage.vhd"
#    "/home/kbogt/my_gits/HICCE/hicce-project/VHDL/Combintan_w_header.vhd"
#    "/home/kbogt/my_gits/HICCE/hicce-project/VHDL/Top.vhd"
#    "/home/kbogt/my_gits/HICCE/hicce-project/IP/FIFO_64k_16bit_v0/FIFO_64k_16bit_v0.xci"
#    "/home/kbogt/my_gits/HICCE/hicce-project/VHDL/HiCCE_source/intan_RHA_ADC_v0.vhd"
#    "/home/kbogt/my_gits/HICCE/hicce-project/VHDL/CombIntan.vhd"
#    "/home/kbogt/my_gits/HICCE/hicce-project/VHDL/rise_edge_detector.vhd"
#    "/home/kbogt/my_gits/HICCE/hicce-project/Const/HiCCE2022_constraints.xdc"
#
#*****************************************************************************************

# Check file required for this script exists
proc checkRequiredFiles { origin_dir} {
  set status true
  set files [list \
 "[file normalize "$origin_dir/hicce_w_header/hicce_w_header.srcs/utils_1/imports/synth_1/HICCEv2_w_header_wrapper.dcp"]"\
  ]
  foreach ifile $files {
    if { ![file isfile $ifile] } {
      puts " Could not find local file $ifile "
      set status false
    }
  }

  set files [list \
 "[file normalize "$origin_dir/VHDL/Sync_count.vhd"]"\
 "[file normalize "$origin_dir/VHDL/ad7982_cnv.vhd"]"\
 "[file normalize "$origin_dir/VHDL/HiCCE_source/intan_RHA_ADC_v1.vhd"]"\
 "[file normalize "$origin_dir/VHDL/spi_master.vhd"]"\
 "[file normalize "$origin_dir/VHDL/HiCCE_source/HiCCEv2_v2022.vhd"]"\
 "[file normalize "$origin_dir/VHDL/counter64.vhd"]"\
 "[file normalize "$origin_dir/VHDL/Timestamp.vhd"]"\
 "[file normalize "$origin_dir/VHDL/Trace_storage.vhd"]"\
 "[file normalize "$origin_dir/VHDL/Combintan_w_header.vhd"]"\
 "[file normalize "$origin_dir/VHDL/Top.vhd"]"\
 "[file normalize "$origin_dir/IP/FIFO_64k_16bit_v0/FIFO_64k_16bit_v0.xci"]"\
 "[file normalize "$origin_dir/VHDL/HiCCE_source/intan_RHA_ADC_v0.vhd"]"\
 "[file normalize "$origin_dir/VHDL/CombIntan.vhd"]"\
 "[file normalize "$origin_dir/VHDL/rise_edge_detector.vhd"]"\
 "[file normalize "$origin_dir/Const/HiCCE2022_constraints.xdc"]"\
  ]
  foreach ifile $files {
    if { ![file isfile $ifile] } {
      puts " Could not find remote file $ifile "
      set status false
    }
  }

  set paths [list \
 "[file normalize "$origin_dir/[file normalize "$origin_dir/IP/core-comblock"]"]"\
  ]
  foreach ipath $paths {
    if { ![file isdirectory $ipath] } {
      puts " Could not access $ipath "
      set status false
    }
  }

  return $status
}
# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "hicce_w_header"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "hicce_w_header.tcl"

# Help information for this script
proc print_help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { print_help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/hicce_w_header"]"

# Check for paths and files needed for project creation
set validate_required 0
if { $validate_required } {
  if { [checkRequiredFiles $origin_dir] } {
    puts "Tcl file $script_file is valid. All files required for project creation is accesable. "
  } else {
    puts "Tcl file $script_file is not valid. Not all files required for project creation is accesable. "
    return
  }
}

# Create project
create_project ${_xil_proj_name_} ./${_xil_proj_name_} -part xc7z020clg484-1

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [current_project]
set_property -name "board_part_repo_paths" -value "[file normalize "$origin_dir/../../../.Xilinx/Vivado/2022.1/xhub/board_store/xilinx_board_store"]" -objects $obj
set_property -name "board_part" -value "avnet.com:zedboard:part0:1.4" -objects $obj
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "enable_resource_estimation" -value "0" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "platform.board_id" -value "zedboard" -objects $obj
set_property -name "revised_directory_structure" -value "1" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "sim_compile_state" -value "1" -objects $obj
set_property -name "target_language" -value "VHDL" -objects $obj
set_property -name "webtalk.activehdl_export_sim" -value "21" -objects $obj
set_property -name "webtalk.modelsim_export_sim" -value "21" -objects $obj
set_property -name "webtalk.questa_export_sim" -value "21" -objects $obj
set_property -name "webtalk.riviera_export_sim" -value "21" -objects $obj
set_property -name "webtalk.vcs_export_sim" -value "21" -objects $obj
set_property -name "webtalk.xsim_export_sim" -value "21" -objects $obj
set_property -name "xpm_libraries" -value "XPM_CDC XPM_MEMORY" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set IP repository paths
set obj [get_filesets sources_1]
if { $obj != {} } {
   set_property "ip_repo_paths" "[file normalize "$origin_dir/IP/core-comblock"]" $obj

   # Rebuild user ip_repo's index before adding any source files
   update_ip_catalog -rebuild
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/VHDL/Sync_count.vhd"] \
 [file normalize "${origin_dir}/VHDL/ad7982_cnv.vhd"] \
 [file normalize "${origin_dir}/VHDL/HiCCE_source/intan_RHA_ADC_v1.vhd"] \
 [file normalize "${origin_dir}/VHDL/spi_master.vhd"] \
 [file normalize "${origin_dir}/VHDL/HiCCE_source/HiCCEv2_v2022.vhd"] \
 [file normalize "${origin_dir}/VHDL/counter64.vhd"] \
 [file normalize "${origin_dir}/VHDL/Timestamp.vhd"] \
 [file normalize "${origin_dir}/VHDL/Trace_storage.vhd"] \
 [file normalize "${origin_dir}/VHDL/Combintan_w_header.vhd"] \
 [file normalize "${origin_dir}/VHDL/Top.vhd"] \
 [file normalize "${origin_dir}/IP/FIFO_64k_16bit_v0/FIFO_64k_16bit_v0.xci"] \
 [file normalize "${origin_dir}/VHDL/HiCCE_source/intan_RHA_ADC_v0.vhd"] \
 [file normalize "${origin_dir}/VHDL/CombIntan.vhd"] \
 [file normalize "${origin_dir}/VHDL/rise_edge_detector.vhd"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/VHDL/Sync_count.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/VHDL/ad7982_cnv.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/VHDL/HiCCE_source/intan_RHA_ADC_v1.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/VHDL/spi_master.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/VHDL/HiCCE_source/HiCCEv2_v2022.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/VHDL/counter64.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/VHDL/Timestamp.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/VHDL/Trace_storage.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/VHDL/Combintan_w_header.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/VHDL/Top.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/IP/FIFO_64k_16bit_v0/FIFO_64k_16bit_v0.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "generate_synth_checkpoint" -value "0" -objects $file_obj
}
set_property -name "registered_with_manager" -value "1" -objects $file_obj

set file "$origin_dir/VHDL/HiCCE_source/intan_RHA_ADC_v0.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/VHDL/CombIntan.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/VHDL/rise_edge_detector.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "dataflow_viewer_settings" -value "min_width=16" -objects $obj
set_property -name "top" -value "HICCEv2_w_header_wrapper" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/Const/HiCCE2022_constraints.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/Const/HiCCE2022_constraints.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "top" -value "HiCCEv2_v2022" -objects $obj
set_property -name "top_arch" -value "Behavioral" -objects $obj
set_property -name "top_file" -value "VHDL/HiCCE_source/HiCCEv2_v2022.vhd" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj

# Set 'utils_1' fileset object
set obj [get_filesets utils_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/hicce_w_header/hicce_w_header.srcs/utils_1/imports/synth_1/HICCEv2_w_header_wrapper.dcp" ]\
]
set imported_files [import_files -fileset utils_1 $files]

# Set 'utils_1' fileset file properties for remote files
# None

# Set 'utils_1' fileset file properties for local files
set file "synth_1/HICCEv2_w_header_wrapper.dcp"
set file_obj [get_files -of_objects [get_filesets utils_1] [list "*$file"]]
set_property -name "netlist_only" -value "0" -objects $file_obj


# Set 'utils_1' fileset properties
set obj [get_filesets utils_1]


# Adding sources referenced in BDs, if not already added
if { [get_files Sync_count.vhd] == "" } {
  import_files -quiet -fileset sources_1 /home/kbogt/my_gits/HICCE/hicce-project/VHDL/Sync_count.vhd
}
if { [get_files ad7982_cnv.vhd] == "" } {
  import_files -quiet -fileset sources_1 /home/kbogt/my_gits/HICCE/hicce-project/VHDL/ad7982_cnv.vhd
}
if { [get_files intan_RHA_ADC_v1.vhd] == "" } {
  import_files -quiet -fileset sources_1 /home/kbogt/my_gits/HICCE/hicce-project/VHDL/HiCCE_source/intan_RHA_ADC_v1.vhd
}
if { [get_files spi_master.vhd] == "" } {
  import_files -quiet -fileset sources_1 /home/kbogt/my_gits/HICCE/hicce-project/VHDL/spi_master.vhd
}
if { [get_files HiCCEv2_v2022.vhd] == "" } {
  import_files -quiet -fileset sources_1 /home/kbogt/my_gits/HICCE/hicce-project/VHDL/HiCCE_source/HiCCEv2_v2022.vhd
}
if { [get_files counter64.vhd] == "" } {
  import_files -quiet -fileset sources_1 /home/kbogt/my_gits/HICCE/hicce-project/VHDL/counter64.vhd
}
if { [get_files Timestamp.vhd] == "" } {
  import_files -quiet -fileset sources_1 /home/kbogt/my_gits/HICCE/hicce-project/VHDL/Timestamp.vhd
}
if { [get_files Trace_storage.vhd] == "" } {
  import_files -quiet -fileset sources_1 /home/kbogt/my_gits/HICCE/hicce-project/VHDL/Trace_storage.vhd
}
if { [get_files Combintan_w_header.vhd] == "" } {
  import_files -quiet -fileset sources_1 /home/kbogt/my_gits/HICCE/hicce-project/VHDL/Combintan_w_header.vhd
}


# Proc to create BD HICCEv2_w_header
proc cr_bd_HICCEv2_w_header { parentCell } {
# The design that will be created by this Tcl proc contains the following 
# module references:
# CombIntan_w_header, HiCCEv2_v2022, counter64



  # CHANGE DESIGN NAME HERE
  set design_name HICCEv2_w_header

  common::send_gid_msg -ssname BD::TCL -id 2010 -severity "INFO" "Currently there is no design <$design_name> in project, so creating one..."

  create_bd_design $design_name

  set bCheckIPsPassed 1
  ##################################################################
  # CHECK IPs
  ##################################################################
  set bCheckIPs 1
  if { $bCheckIPs == 1 } {
     set list_check_ips "\ 
  xilinx.com:ip:util_vector_logic:2.0\
  www.ictp.it:user:comblock:2.0\
  xilinx.com:ip:processing_system7:5.5\
  xilinx.com:ip:proc_sys_reset:5.0\
  xilinx.com:ip:system_ila:1.1\
  xilinx.com:ip:xlconstant:1.1\
  "

   set list_ips_missing ""
   common::send_gid_msg -ssname BD::TCL -id 2011 -severity "INFO" "Checking if the following IPs exist in the project's IP catalog: $list_check_ips ."

   foreach ip_vlnv $list_check_ips {
      set ip_obj [get_ipdefs -all $ip_vlnv]
      if { $ip_obj eq "" } {
         lappend list_ips_missing $ip_vlnv
      }
   }

   if { $list_ips_missing ne "" } {
      catch {common::send_gid_msg -ssname BD::TCL -id 2012 -severity "ERROR" "The following IPs are not found in the IP Catalog:\n  $list_ips_missing\n\nResolution: Please add the repository containing the IP(s) to the project." }
      set bCheckIPsPassed 0
   }

  }

  ##################################################################
  # CHECK Modules
  ##################################################################
  set bCheckModules 1
  if { $bCheckModules == 1 } {
     set list_check_mods "\ 
  CombIntan_w_header\
  HiCCEv2_v2022\
  counter64\
  "

   set list_mods_missing ""
   common::send_gid_msg -ssname BD::TCL -id 2020 -severity "INFO" "Checking if the following modules exist in the project's sources: $list_check_mods ."

   foreach mod_vlnv $list_check_mods {
      if { [can_resolve_reference $mod_vlnv] == 0 } {
         lappend list_mods_missing $mod_vlnv
      }
   }

   if { $list_mods_missing ne "" } {
      catch {common::send_gid_msg -ssname BD::TCL -id 2021 -severity "ERROR" "The following module(s) are not found in the project: $list_mods_missing" }
      common::send_gid_msg -ssname BD::TCL -id 2022 -severity "INFO" "Please add source files for the missing module(s) above."
      set bCheckIPsPassed 0
   }
}

  if { $bCheckIPsPassed != 1 } {
    common::send_gid_msg -ssname BD::TCL -id 2023 -severity "WARNING" "Will not continue with creation of design due to the error(s) above."
    return 3
  }

  variable script_folder

  if { $parentCell eq "" } {
     set parentCell [get_bd_cells /]
  }

  # Get object for parentCell
  set parentObj [get_bd_cells $parentCell]
  if { $parentObj == "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2090 -severity "ERROR" "Unable to find parent cell <$parentCell>!"}
     return
  }

  # Make sure parentObj is hier blk
  set parentType [get_property TYPE $parentObj]
  if { $parentType ne "hier" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2091 -severity "ERROR" "Parent <$parentObj> has TYPE = <$parentType>. Expected to be <hier>."}
     return
  }

  # Save current instance; Restore later
  set oldCurInst [current_bd_instance .]

  # Set parent object as current
  current_bd_instance $parentObj


  # Create interface ports
  set DDR [ create_bd_intf_port -mode Master -vlnv xilinx.com:interface:ddrx_rtl:1.0 DDR ]

  set FIXED_IO [ create_bd_intf_port -mode Master -vlnv xilinx.com:display_processing_system7:fixedio_rtl:1.0 FIXED_IO ]


  # Create ports
  set ADC_CNV_0 [ create_bd_port -dir O -from 3 -to 0 ADC_CNV_0 ]
  set ADC_SCLK_0 [ create_bd_port -dir O -from 3 -to 0 ADC_SCLK_0 ]
  set ADC_SDO_0 [ create_bd_port -dir I -from 3 -to 0 ADC_SDO_0 ]
  set Conn_All_0 [ create_bd_port -dir O -from 3 -to 0 Conn_All_0 ]
  set Elec_Test_0 [ create_bd_port -dir O -from 3 -to 0 Elec_Test_0 ]
  set Elec_Test_en_0 [ create_bd_port -dir O -from 3 -to 0 Elec_Test_en_0 ]
  set LED_HiCCE_AB_0 [ create_bd_port -dir O -from 1 -to 0 LED_HiCCE_AB_0 ]
  set Mode_0 [ create_bd_port -dir O -from 3 -to 0 Mode_0 ]
  set Sel0_Reset_0 [ create_bd_port -dir O -from 3 -to 0 -type rst Sel0_Reset_0 ]
  set Sel1_Step_0 [ create_bd_port -dir O -from 3 -to 0 Sel1_Step_0 ]
  set Sel2_Sync_0 [ create_bd_port -dir IO -from 3 -to 0 Sel2_Sync_0 ]
  set Sel3_0 [ create_bd_port -dir IO -from 3 -to 0 Sel3_0 ]
  set Sel4_0 [ create_bd_port -dir IO -from 3 -to 0 Sel4_0 ]
  set Settle_0 [ create_bd_port -dir O -from 3 -to 0 Settle_0 ]

  # Create instance: CombIntan_w_header_0, and set properties
  set block_name CombIntan_w_header
  set block_cell_name CombIntan_w_header_0
  if { [catch {set CombIntan_w_header_0 [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2095 -severity "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $CombIntan_w_header_0 eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2096 -severity "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
    set_property CONFIG.FIFO_SIZE {32768} $CombIntan_w_header_0


  # Create instance: HiCCEv2_v2022_0, and set properties
  set block_name HiCCEv2_v2022
  set block_cell_name HiCCEv2_v2022_0
  if { [catch {set HiCCEv2_v2022_0 [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2095 -severity "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $HiCCEv2_v2022_0 eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2096 -severity "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
  
  # Create instance: ab_tready, and set properties
  set ab_tready [ create_bd_cell -type ip -vlnv xilinx.com:ip:util_vector_logic:2.0 ab_tready ]
  set_property -dict [list \
    CONFIG.C_OPERATION {not} \
    CONFIG.C_SIZE {1} \
  ] $ab_tready


  # Create instance: cd_tready, and set properties
  set cd_tready [ create_bd_cell -type ip -vlnv xilinx.com:ip:util_vector_logic:2.0 cd_tready ]
  set_property -dict [list \
    CONFIG.C_OPERATION {not} \
    CONFIG.C_SIZE {1} \
  ] $cd_tready


  # Create instance: comblock_0, and set properties
  set comblock_0 [ create_bd_cell -type ip -vlnv www.ictp.it:user:comblock:2.0 comblock_0 ]
  set_property -dict [list \
    CONFIG.DRAM_IO_ENA {false} \
    CONFIG.FIFO_IN_AEOFFSET {10} \
    CONFIG.FIFO_IN_AFOFFSET {10} \
    CONFIG.FIFO_IN_DEPTH {32768} \
    CONFIG.FIFO_IN_DWIDTH {32} \
    CONFIG.REGS_OUT_DEPTH {8} \
  ] $comblock_0


  # Create instance: comblock_1, and set properties
  set comblock_1 [ create_bd_cell -type ip -vlnv www.ictp.it:user:comblock:2.0 comblock_1 ]
  set_property -dict [list \
    CONFIG.DRAM_IO_ENA {false} \
    CONFIG.FIFO_IN_AEOFFSET {10} \
    CONFIG.FIFO_IN_AFOFFSET {10} \
    CONFIG.FIFO_IN_DEPTH {32768} \
    CONFIG.FIFO_IN_DWIDTH {32} \
    CONFIG.REGS_OUT_DEPTH {8} \
  ] $comblock_1


  # Create instance: counter64_0, and set properties
  set block_name counter64
  set block_cell_name counter64_0
  if { [catch {set counter64_0 [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2095 -severity "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $counter64_0 eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2096 -severity "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
  
  # Create instance: processing_system7_0, and set properties
  set processing_system7_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:processing_system7:5.5 processing_system7_0 ]
  set_property -dict [list \
    CONFIG.PCW_ACT_APU_PERIPHERAL_FREQMHZ {666.666687} \
    CONFIG.PCW_ACT_CAN_PERIPHERAL_FREQMHZ {10.000000} \
    CONFIG.PCW_ACT_DCI_PERIPHERAL_FREQMHZ {10.158730} \
    CONFIG.PCW_ACT_ENET0_PERIPHERAL_FREQMHZ {125.000000} \
    CONFIG.PCW_ACT_ENET1_PERIPHERAL_FREQMHZ {10.000000} \
    CONFIG.PCW_ACT_FPGA0_PERIPHERAL_FREQMHZ {100.000000} \
    CONFIG.PCW_ACT_FPGA1_PERIPHERAL_FREQMHZ {10.000000} \
    CONFIG.PCW_ACT_FPGA2_PERIPHERAL_FREQMHZ {10.000000} \
    CONFIG.PCW_ACT_FPGA3_PERIPHERAL_FREQMHZ {10.000000} \
    CONFIG.PCW_ACT_PCAP_PERIPHERAL_FREQMHZ {200.000000} \
    CONFIG.PCW_ACT_QSPI_PERIPHERAL_FREQMHZ {200.000000} \
    CONFIG.PCW_ACT_SDIO_PERIPHERAL_FREQMHZ {50.000000} \
    CONFIG.PCW_ACT_SMC_PERIPHERAL_FREQMHZ {10.000000} \
    CONFIG.PCW_ACT_SPI_PERIPHERAL_FREQMHZ {10.000000} \
    CONFIG.PCW_ACT_TPIU_PERIPHERAL_FREQMHZ {200.000000} \
    CONFIG.PCW_ACT_TTC0_CLK0_PERIPHERAL_FREQMHZ {111.111115} \
    CONFIG.PCW_ACT_TTC0_CLK1_PERIPHERAL_FREQMHZ {111.111115} \
    CONFIG.PCW_ACT_TTC0_CLK2_PERIPHERAL_FREQMHZ {111.111115} \
    CONFIG.PCW_ACT_TTC1_CLK0_PERIPHERAL_FREQMHZ {111.111115} \
    CONFIG.PCW_ACT_TTC1_CLK1_PERIPHERAL_FREQMHZ {111.111115} \
    CONFIG.PCW_ACT_TTC1_CLK2_PERIPHERAL_FREQMHZ {111.111115} \
    CONFIG.PCW_ACT_UART_PERIPHERAL_FREQMHZ {50.000000} \
    CONFIG.PCW_ACT_WDT_PERIPHERAL_FREQMHZ {111.111115} \
    CONFIG.PCW_APU_PERIPHERAL_FREQMHZ {666.666667} \
    CONFIG.PCW_CLK0_FREQ {100000000} \
    CONFIG.PCW_CLK1_FREQ {10000000} \
    CONFIG.PCW_CLK2_FREQ {10000000} \
    CONFIG.PCW_CLK3_FREQ {10000000} \
    CONFIG.PCW_DDR_RAM_HIGHADDR {0x1FFFFFFF} \
    CONFIG.PCW_ENET0_ENET0_IO {MIO 16 .. 27} \
    CONFIG.PCW_ENET0_GRP_MDIO_ENABLE {1} \
    CONFIG.PCW_ENET0_GRP_MDIO_IO {MIO 52 .. 53} \
    CONFIG.PCW_ENET0_PERIPHERAL_ENABLE {1} \
    CONFIG.PCW_ENET0_PERIPHERAL_FREQMHZ {1000 Mbps} \
    CONFIG.PCW_ENET0_RESET_ENABLE {0} \
    CONFIG.PCW_ENET_RESET_ENABLE {1} \
    CONFIG.PCW_ENET_RESET_SELECT {Share reset pin} \
    CONFIG.PCW_EN_EMIO_TTC0 {1} \
    CONFIG.PCW_EN_ENET0 {1} \
    CONFIG.PCW_EN_GPIO {1} \
    CONFIG.PCW_EN_QSPI {1} \
    CONFIG.PCW_EN_SDIO0 {1} \
    CONFIG.PCW_EN_TTC0 {1} \
    CONFIG.PCW_EN_UART1 {1} \
    CONFIG.PCW_EN_USB0 {1} \
    CONFIG.PCW_FPGA0_PERIPHERAL_FREQMHZ {100.000000} \
    CONFIG.PCW_FPGA1_PERIPHERAL_FREQMHZ {150.000000} \
    CONFIG.PCW_FPGA2_PERIPHERAL_FREQMHZ {50.000000} \
    CONFIG.PCW_FPGA_FCLK0_ENABLE {1} \
    CONFIG.PCW_GPIO_MIO_GPIO_ENABLE {1} \
    CONFIG.PCW_GPIO_MIO_GPIO_IO {MIO} \
    CONFIG.PCW_I2C0_PERIPHERAL_ENABLE {0} \
    CONFIG.PCW_I2C_RESET_ENABLE {1} \
    CONFIG.PCW_MIO_0_IOTYPE {LVCMOS 3.3V} \
    CONFIG.PCW_MIO_0_PULLUP {disabled} \
    CONFIG.PCW_MIO_0_SLEW {slow} \
    CONFIG.PCW_MIO_10_IOTYPE {LVCMOS 3.3V} \
    CONFIG.PCW_MIO_10_PULLUP {disabled} \
    CONFIG.PCW_MIO_10_SLEW {slow} \
    CONFIG.PCW_MIO_11_IOTYPE {LVCMOS 3.3V} \
    CONFIG.PCW_MIO_11_PULLUP {disabled} \
    CONFIG.PCW_MIO_11_SLEW {slow} \
    CONFIG.PCW_MIO_12_IOTYPE {LVCMOS 3.3V} \
    CONFIG.PCW_MIO_12_PULLUP {disabled} \
    CONFIG.PCW_MIO_12_SLEW {slow} \
    CONFIG.PCW_MIO_13_IOTYPE {LVCMOS 3.3V} \
    CONFIG.PCW_MIO_13_PULLUP {disabled} \
    CONFIG.PCW_MIO_13_SLEW {slow} \
    CONFIG.PCW_MIO_14_IOTYPE {LVCMOS 3.3V} \
    CONFIG.PCW_MIO_14_PULLUP {disabled} \
    CONFIG.PCW_MIO_14_SLEW {slow} \
    CONFIG.PCW_MIO_15_IOTYPE {LVCMOS 3.3V} \
    CONFIG.PCW_MIO_15_PULLUP {disabled} \
    CONFIG.PCW_MIO_15_SLEW {slow} \
    CONFIG.PCW_MIO_16_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_16_PULLUP {disabled} \
    CONFIG.PCW_MIO_16_SLEW {fast} \
    CONFIG.PCW_MIO_17_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_17_PULLUP {disabled} \
    CONFIG.PCW_MIO_17_SLEW {fast} \
    CONFIG.PCW_MIO_18_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_18_PULLUP {disabled} \
    CONFIG.PCW_MIO_18_SLEW {fast} \
    CONFIG.PCW_MIO_19_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_19_PULLUP {disabled} \
    CONFIG.PCW_MIO_19_SLEW {fast} \
    CONFIG.PCW_MIO_1_IOTYPE {LVCMOS 3.3V} \
    CONFIG.PCW_MIO_1_PULLUP {disabled} \
    CONFIG.PCW_MIO_1_SLEW {fast} \
    CONFIG.PCW_MIO_20_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_20_PULLUP {disabled} \
    CONFIG.PCW_MIO_20_SLEW {fast} \
    CONFIG.PCW_MIO_21_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_21_PULLUP {disabled} \
    CONFIG.PCW_MIO_21_SLEW {fast} \
    CONFIG.PCW_MIO_22_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_22_PULLUP {disabled} \
    CONFIG.PCW_MIO_22_SLEW {fast} \
    CONFIG.PCW_MIO_23_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_23_PULLUP {disabled} \
    CONFIG.PCW_MIO_23_SLEW {fast} \
    CONFIG.PCW_MIO_24_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_24_PULLUP {disabled} \
    CONFIG.PCW_MIO_24_SLEW {fast} \
    CONFIG.PCW_MIO_25_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_25_PULLUP {disabled} \
    CONFIG.PCW_MIO_25_SLEW {fast} \
    CONFIG.PCW_MIO_26_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_26_PULLUP {disabled} \
    CONFIG.PCW_MIO_26_SLEW {fast} \
    CONFIG.PCW_MIO_27_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_27_PULLUP {disabled} \
    CONFIG.PCW_MIO_27_SLEW {fast} \
    CONFIG.PCW_MIO_28_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_28_PULLUP {disabled} \
    CONFIG.PCW_MIO_28_SLEW {fast} \
    CONFIG.PCW_MIO_29_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_29_PULLUP {disabled} \
    CONFIG.PCW_MIO_29_SLEW {fast} \
    CONFIG.PCW_MIO_2_IOTYPE {LVCMOS 3.3V} \
    CONFIG.PCW_MIO_2_SLEW {fast} \
    CONFIG.PCW_MIO_30_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_30_PULLUP {disabled} \
    CONFIG.PCW_MIO_30_SLEW {fast} \
    CONFIG.PCW_MIO_31_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_31_PULLUP {disabled} \
    CONFIG.PCW_MIO_31_SLEW {fast} \
    CONFIG.PCW_MIO_32_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_32_PULLUP {disabled} \
    CONFIG.PCW_MIO_32_SLEW {fast} \
    CONFIG.PCW_MIO_33_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_33_PULLUP {disabled} \
    CONFIG.PCW_MIO_33_SLEW {fast} \
    CONFIG.PCW_MIO_34_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_34_PULLUP {disabled} \
    CONFIG.PCW_MIO_34_SLEW {fast} \
    CONFIG.PCW_MIO_35_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_35_PULLUP {disabled} \
    CONFIG.PCW_MIO_35_SLEW {fast} \
    CONFIG.PCW_MIO_36_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_36_PULLUP {disabled} \
    CONFIG.PCW_MIO_36_SLEW {fast} \
    CONFIG.PCW_MIO_37_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_37_PULLUP {disabled} \
    CONFIG.PCW_MIO_37_SLEW {fast} \
    CONFIG.PCW_MIO_38_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_38_PULLUP {disabled} \
    CONFIG.PCW_MIO_38_SLEW {fast} \
    CONFIG.PCW_MIO_39_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_39_PULLUP {disabled} \
    CONFIG.PCW_MIO_39_SLEW {fast} \
    CONFIG.PCW_MIO_3_IOTYPE {LVCMOS 3.3V} \
    CONFIG.PCW_MIO_3_SLEW {fast} \
    CONFIG.PCW_MIO_40_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_40_PULLUP {disabled} \
    CONFIG.PCW_MIO_40_SLEW {fast} \
    CONFIG.PCW_MIO_41_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_41_PULLUP {disabled} \
    CONFIG.PCW_MIO_41_SLEW {fast} \
    CONFIG.PCW_MIO_42_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_42_PULLUP {disabled} \
    CONFIG.PCW_MIO_42_SLEW {fast} \
    CONFIG.PCW_MIO_43_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_43_PULLUP {disabled} \
    CONFIG.PCW_MIO_43_SLEW {fast} \
    CONFIG.PCW_MIO_44_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_44_PULLUP {disabled} \
    CONFIG.PCW_MIO_44_SLEW {fast} \
    CONFIG.PCW_MIO_45_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_45_PULLUP {disabled} \
    CONFIG.PCW_MIO_45_SLEW {fast} \
    CONFIG.PCW_MIO_46_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_46_PULLUP {disabled} \
    CONFIG.PCW_MIO_46_SLEW {slow} \
    CONFIG.PCW_MIO_47_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_47_PULLUP {disabled} \
    CONFIG.PCW_MIO_47_SLEW {slow} \
    CONFIG.PCW_MIO_48_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_48_PULLUP {disabled} \
    CONFIG.PCW_MIO_48_SLEW {slow} \
    CONFIG.PCW_MIO_49_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_49_PULLUP {disabled} \
    CONFIG.PCW_MIO_49_SLEW {slow} \
    CONFIG.PCW_MIO_4_IOTYPE {LVCMOS 3.3V} \
    CONFIG.PCW_MIO_4_SLEW {fast} \
    CONFIG.PCW_MIO_50_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_50_PULLUP {disabled} \
    CONFIG.PCW_MIO_50_SLEW {slow} \
    CONFIG.PCW_MIO_51_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_51_PULLUP {disabled} \
    CONFIG.PCW_MIO_51_SLEW {slow} \
    CONFIG.PCW_MIO_52_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_52_PULLUP {disabled} \
    CONFIG.PCW_MIO_52_SLEW {slow} \
    CONFIG.PCW_MIO_53_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_53_PULLUP {disabled} \
    CONFIG.PCW_MIO_53_SLEW {slow} \
    CONFIG.PCW_MIO_5_IOTYPE {LVCMOS 3.3V} \
    CONFIG.PCW_MIO_5_SLEW {fast} \
    CONFIG.PCW_MIO_6_IOTYPE {LVCMOS 3.3V} \
    CONFIG.PCW_MIO_6_SLEW {fast} \
    CONFIG.PCW_MIO_7_IOTYPE {LVCMOS 3.3V} \
    CONFIG.PCW_MIO_7_SLEW {slow} \
    CONFIG.PCW_MIO_8_IOTYPE {LVCMOS 3.3V} \
    CONFIG.PCW_MIO_8_SLEW {fast} \
    CONFIG.PCW_MIO_9_IOTYPE {LVCMOS 3.3V} \
    CONFIG.PCW_MIO_9_PULLUP {disabled} \
    CONFIG.PCW_MIO_9_SLEW {slow} \
    CONFIG.PCW_MIO_TREE_PERIPHERALS {GPIO#Quad SPI Flash#Quad SPI Flash#Quad SPI Flash#Quad SPI Flash#Quad SPI Flash#Quad SPI Flash#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#Enet 0#Enet 0#Enet 0#Enet\
0#Enet 0#Enet 0#Enet 0#Enet 0#Enet 0#Enet 0#Enet 0#Enet 0#USB 0#USB 0#USB 0#USB 0#USB 0#USB 0#USB 0#USB 0#USB 0#USB 0#USB 0#USB 0#SD 0#SD 0#SD 0#SD 0#SD 0#SD 0#SD 0#SD 0#UART 1#UART 1#GPIO#GPIO#Enet 0#Enet\
0} \
    CONFIG.PCW_MIO_TREE_SIGNALS {gpio[0]#qspi0_ss_b#qspi0_io[0]#qspi0_io[1]#qspi0_io[2]#qspi0_io[3]/HOLD_B#qspi0_sclk#gpio[7]#gpio[8]#gpio[9]#gpio[10]#gpio[11]#gpio[12]#gpio[13]#gpio[14]#gpio[15]#tx_clk#txd[0]#txd[1]#txd[2]#txd[3]#tx_ctl#rx_clk#rxd[0]#rxd[1]#rxd[2]#rxd[3]#rx_ctl#data[4]#dir#stp#nxt#data[0]#data[1]#data[2]#data[3]#clk#data[5]#data[6]#data[7]#clk#cmd#data[0]#data[1]#data[2]#data[3]#wp#cd#tx#rx#gpio[50]#gpio[51]#mdc#mdio}\
\
    CONFIG.PCW_PJTAG_PERIPHERAL_ENABLE {0} \
    CONFIG.PCW_PRESET_BANK0_VOLTAGE {LVCMOS 3.3V} \
    CONFIG.PCW_PRESET_BANK1_VOLTAGE {LVCMOS 1.8V} \
    CONFIG.PCW_QSPI_GRP_FBCLK_ENABLE {0} \
    CONFIG.PCW_QSPI_GRP_IO1_ENABLE {0} \
    CONFIG.PCW_QSPI_GRP_SINGLE_SS_ENABLE {1} \
    CONFIG.PCW_QSPI_GRP_SINGLE_SS_IO {MIO 1 .. 6} \
    CONFIG.PCW_QSPI_GRP_SS1_ENABLE {0} \
    CONFIG.PCW_QSPI_PERIPHERAL_ENABLE {1} \
    CONFIG.PCW_QSPI_PERIPHERAL_FREQMHZ {200.000000} \
    CONFIG.PCW_QSPI_QSPI_IO {MIO 1 .. 6} \
    CONFIG.PCW_SD0_GRP_CD_ENABLE {1} \
    CONFIG.PCW_SD0_GRP_CD_IO {MIO 47} \
    CONFIG.PCW_SD0_GRP_POW_ENABLE {0} \
    CONFIG.PCW_SD0_GRP_WP_ENABLE {1} \
    CONFIG.PCW_SD0_GRP_WP_IO {MIO 46} \
    CONFIG.PCW_SD0_PERIPHERAL_ENABLE {1} \
    CONFIG.PCW_SD0_SD0_IO {MIO 40 .. 45} \
    CONFIG.PCW_SDIO_PERIPHERAL_FREQMHZ {50} \
    CONFIG.PCW_SDIO_PERIPHERAL_VALID {1} \
    CONFIG.PCW_SINGLE_QSPI_DATA_MODE {x4} \
    CONFIG.PCW_TTC0_PERIPHERAL_ENABLE {1} \
    CONFIG.PCW_TTC0_TTC0_IO {EMIO} \
    CONFIG.PCW_TTC_PERIPHERAL_FREQMHZ {50} \
    CONFIG.PCW_UART1_GRP_FULL_ENABLE {0} \
    CONFIG.PCW_UART1_PERIPHERAL_ENABLE {1} \
    CONFIG.PCW_UART1_UART1_IO {MIO 48 .. 49} \
    CONFIG.PCW_UART_PERIPHERAL_FREQMHZ {50} \
    CONFIG.PCW_UART_PERIPHERAL_VALID {1} \
    CONFIG.PCW_UIPARAM_ACT_DDR_FREQ_MHZ {533.333374} \
    CONFIG.PCW_UIPARAM_DDR_BL {8} \
    CONFIG.PCW_UIPARAM_DDR_BOARD_DELAY0 {0.41} \
    CONFIG.PCW_UIPARAM_DDR_BOARD_DELAY1 {0.411} \
    CONFIG.PCW_UIPARAM_DDR_BOARD_DELAY2 {0.341} \
    CONFIG.PCW_UIPARAM_DDR_BOARD_DELAY3 {0.358} \
    CONFIG.PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_0 {0.025} \
    CONFIG.PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_1 {0.028} \
    CONFIG.PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_2 {0.001} \
    CONFIG.PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_3 {0.001} \
    CONFIG.PCW_UIPARAM_DDR_FREQ_MHZ {533.333313} \
    CONFIG.PCW_UIPARAM_DDR_MEMORY_TYPE {DDR 3} \
    CONFIG.PCW_UIPARAM_DDR_PARTNO {MT41J128M16 HA-15E} \
    CONFIG.PCW_UIPARAM_DDR_TRAIN_DATA_EYE {1} \
    CONFIG.PCW_UIPARAM_DDR_TRAIN_READ_GATE {1} \
    CONFIG.PCW_UIPARAM_DDR_TRAIN_WRITE_LEVEL {1} \
    CONFIG.PCW_UIPARAM_DDR_USE_INTERNAL_VREF {1} \
    CONFIG.PCW_USB0_PERIPHERAL_ENABLE {1} \
    CONFIG.PCW_USB0_RESET_ENABLE {0} \
    CONFIG.PCW_USB0_USB0_IO {MIO 28 .. 39} \
    CONFIG.PCW_USB_RESET_ENABLE {1} \
    CONFIG.PCW_USB_RESET_SELECT {Share reset pin} \
    CONFIG.preset {ZedBoard} \
  ] $processing_system7_0


  # Create instance: ps7_0_axi_periph, and set properties
  set ps7_0_axi_periph [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_interconnect:2.1 ps7_0_axi_periph ]
  set_property CONFIG.NUM_MI {2} $ps7_0_axi_periph


  # Create instance: rst_ps7_0_100M, and set properties
  set rst_ps7_0_100M [ create_bd_cell -type ip -vlnv xilinx.com:ip:proc_sys_reset:5.0 rst_ps7_0_100M ]

  # Create instance: system_ila_0, and set properties
  set system_ila_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:system_ila:1.1 system_ila_0 ]
  set_property -dict [list \
    CONFIG.C_MON_TYPE {NATIVE} \
    CONFIG.C_NUM_OF_PROBES {31} \
    CONFIG.C_PROBE0_TYPE {0} \
    CONFIG.C_PROBE10_TYPE {0} \
    CONFIG.C_PROBE11_TYPE {0} \
    CONFIG.C_PROBE12_TYPE {0} \
    CONFIG.C_PROBE13_TYPE {0} \
    CONFIG.C_PROBE14_TYPE {0} \
    CONFIG.C_PROBE15_TYPE {0} \
    CONFIG.C_PROBE16_TYPE {0} \
    CONFIG.C_PROBE17_TYPE {0} \
    CONFIG.C_PROBE18_TYPE {0} \
    CONFIG.C_PROBE19_TYPE {0} \
    CONFIG.C_PROBE1_TYPE {0} \
    CONFIG.C_PROBE20_TYPE {0} \
    CONFIG.C_PROBE21_TYPE {0} \
    CONFIG.C_PROBE22_TYPE {0} \
    CONFIG.C_PROBE23_TYPE {0} \
    CONFIG.C_PROBE24_TYPE {0} \
    CONFIG.C_PROBE25_TYPE {0} \
    CONFIG.C_PROBE26_TYPE {0} \
    CONFIG.C_PROBE27_TYPE {0} \
    CONFIG.C_PROBE28_TYPE {0} \
    CONFIG.C_PROBE29_TYPE {0} \
    CONFIG.C_PROBE2_TYPE {0} \
    CONFIG.C_PROBE30_TYPE {0} \
    CONFIG.C_PROBE3_TYPE {0} \
    CONFIG.C_PROBE4_TYPE {0} \
    CONFIG.C_PROBE5_TYPE {0} \
    CONFIG.C_PROBE6_TYPE {0} \
    CONFIG.C_PROBE7_TYPE {0} \
    CONFIG.C_PROBE8_TYPE {0} \
    CONFIG.C_PROBE9_TYPE {0} \
  ] $system_ila_0


  # Create instance: util_vector_logic_0, and set properties
  set util_vector_logic_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:util_vector_logic:2.0 util_vector_logic_0 ]
  set_property CONFIG.C_SIZE {1} $util_vector_logic_0


  # Create instance: xlconstant_0, and set properties
  set xlconstant_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:xlconstant:1.1 xlconstant_0 ]

  # Create interface connections
  connect_bd_intf_net -intf_net processing_system7_0_DDR [get_bd_intf_ports DDR] [get_bd_intf_pins processing_system7_0/DDR]
  connect_bd_intf_net -intf_net processing_system7_0_FIXED_IO [get_bd_intf_ports FIXED_IO] [get_bd_intf_pins processing_system7_0/FIXED_IO]
  connect_bd_intf_net -intf_net processing_system7_0_M_AXI_GP0 [get_bd_intf_pins processing_system7_0/M_AXI_GP0] [get_bd_intf_pins ps7_0_axi_periph/S00_AXI]
  connect_bd_intf_net -intf_net ps7_0_axi_periph_M00_AXI [get_bd_intf_pins comblock_0/AXIL] [get_bd_intf_pins ps7_0_axi_periph/M00_AXI]
  connect_bd_intf_net -intf_net ps7_0_axi_periph_M01_AXI [get_bd_intf_pins comblock_1/AXIL] [get_bd_intf_pins ps7_0_axi_periph/M01_AXI]

  # Create port connections
  connect_bd_net -net ADC_SDO_0_1 [get_bd_ports ADC_SDO_0] [get_bd_pins HiCCEv2_v2022_0/ADC_SDO] [get_bd_pins system_ila_0/probe1]
  set_property HDL_ATTRIBUTE.DEBUG {true} [get_bd_nets ADC_SDO_0_1]
  connect_bd_net -net CLK_SWITCH_INT_A [get_bd_pins HiCCEv2_v2022_0/CLK_SWITCH_INT_A]
  connect_bd_net -net CLK_SWITCH_INT_B [get_bd_pins HiCCEv2_v2022_0/CLK_SWITCH_INT_B]
  connect_bd_net -net CLK_SWITCH_INT_C [get_bd_pins HiCCEv2_v2022_0/CLK_SWITCH_INT_C]
  connect_bd_net -net CLK_SWITCH_INT_D [get_bd_pins HiCCEv2_v2022_0/CLK_SWITCH_INT_D]
  connect_bd_net -net CombIntan_w_header_0_FIFO_CLEAR_AB [get_bd_pins CombIntan_w_header_0/FIFO_CLEAR_AB] [get_bd_pins comblock_0/fifo_clear_i]
  connect_bd_net -net CombIntan_w_header_0_FIFO_CLEAR_CD [get_bd_pins CombIntan_w_header_0/FIFO_CLEAR_CD] [get_bd_pins comblock_1/fifo_clear_i]
  connect_bd_net -net CombIntan_w_header_0_ab_maxis_tdata [get_bd_pins CombIntan_w_header_0/ab_maxis_tdata] [get_bd_pins comblock_0/fifo_data_i] [get_bd_pins system_ila_0/probe3]
  set_property HDL_ATTRIBUTE.DEBUG {true} [get_bd_nets CombIntan_w_header_0_ab_maxis_tdata]
  connect_bd_net -net CombIntan_w_header_0_ab_maxis_tvalid [get_bd_pins CombIntan_w_header_0/ab_maxis_tvalid] [get_bd_pins comblock_0/fifo_we_i] [get_bd_pins system_ila_0/probe4]
  set_property HDL_ATTRIBUTE.DEBUG {true} [get_bd_nets CombIntan_w_header_0_ab_maxis_tvalid]
  connect_bd_net -net CombIntan_w_header_0_cd_maxis_tdata [get_bd_pins CombIntan_w_header_0/cd_maxis_tdata] [get_bd_pins comblock_1/fifo_data_i] [get_bd_pins system_ila_0/probe5]
  set_property HDL_ATTRIBUTE.DEBUG {true} [get_bd_nets CombIntan_w_header_0_cd_maxis_tdata]
  connect_bd_net -net CombIntan_w_header_0_cd_maxis_tvalid [get_bd_pins CombIntan_w_header_0/cd_maxis_tvalid] [get_bd_pins comblock_1/fifo_we_i] [get_bd_pins system_ila_0/probe6]
  set_property HDL_ATTRIBUTE.DEBUG {true} [get_bd_nets CombIntan_w_header_0_cd_maxis_tvalid]
  connect_bd_net -net DBG_COUNT_AB [get_bd_pins CombIntan_w_header_0/DBG_COUNT_AB] [get_bd_pins system_ila_0/probe13]
  set_property HDL_ATTRIBUTE.DEBUG {true} [get_bd_nets DBG_COUNT_AB]
  connect_bd_net -net DBG_COUNT_CD [get_bd_pins CombIntan_w_header_0/DBG_COUNT_CD] [get_bd_pins system_ila_0/probe14]
  set_property HDL_ATTRIBUTE.DEBUG {true} [get_bd_nets DBG_COUNT_CD]
  connect_bd_net -net DBG_MAX_COUNT_AB [get_bd_pins CombIntan_w_header_0/DBG_MAX_COUNT_AB] [get_bd_pins system_ila_0/probe15]
  set_property HDL_ATTRIBUTE.DEBUG {true} [get_bd_nets DBG_MAX_COUNT_AB]
  connect_bd_net -net DBG_MAX_COUNT_CD [get_bd_pins CombIntan_w_header_0/DBG_MAX_COUNT_CD] [get_bd_pins system_ila_0/probe16]
  set_property HDL_ATTRIBUTE.DEBUG {true} [get_bd_nets DBG_MAX_COUNT_CD]
  connect_bd_net -net DBG_STATE_AB [get_bd_pins CombIntan_w_header_0/DBG_STATE_AB] [get_bd_pins system_ila_0/probe17]
  set_property HDL_ATTRIBUTE.DEBUG {true} [get_bd_nets DBG_STATE_AB]
  connect_bd_net -net DBG_STATE_CD [get_bd_pins CombIntan_w_header_0/DBG_STATE_CD] [get_bd_pins system_ila_0/probe18]
  set_property HDL_ATTRIBUTE.DEBUG {true} [get_bd_nets DBG_STATE_CD]
  connect_bd_net -net HiCCEv2_v2022_0_ADC_CNV [get_bd_ports ADC_CNV_0] [get_bd_pins HiCCEv2_v2022_0/ADC_CNV] [get_bd_pins system_ila_0/probe20]
  set_property HDL_ATTRIBUTE.DEBUG {true} [get_bd_nets HiCCEv2_v2022_0_ADC_CNV]
  connect_bd_net -net HiCCEv2_v2022_0_ADC_SCLK [get_bd_ports ADC_SCLK_0] [get_bd_pins HiCCEv2_v2022_0/ADC_SCLK] [get_bd_pins system_ila_0/probe21]
  set_property HDL_ATTRIBUTE.DEBUG {true} [get_bd_nets HiCCEv2_v2022_0_ADC_SCLK]
  connect_bd_net -net HiCCEv2_v2022_0_Ack_intan [get_bd_pins CombIntan_w_header_0/DataIn_ack] [get_bd_pins HiCCEv2_v2022_0/Ack_intan] [get_bd_pins system_ila_0/probe19]
  set_property HDL_ATTRIBUTE.DEBUG {true} [get_bd_nets HiCCEv2_v2022_0_Ack_intan]
  connect_bd_net -net HiCCEv2_v2022_0_Conn_All [get_bd_ports Conn_All_0] [get_bd_pins HiCCEv2_v2022_0/Conn_All]
  connect_bd_net -net HiCCEv2_v2022_0_Data_intan_A [get_bd_pins CombIntan_w_header_0/DataIn_A] [get_bd_pins HiCCEv2_v2022_0/Data_intan_A] [get_bd_pins system_ila_0/probe22]
  set_property HDL_ATTRIBUTE.DEBUG {true} [get_bd_nets HiCCEv2_v2022_0_Data_intan_A]
  connect_bd_net -net HiCCEv2_v2022_0_Data_intan_B [get_bd_pins CombIntan_w_header_0/DataIn_B] [get_bd_pins HiCCEv2_v2022_0/Data_intan_B] [get_bd_pins system_ila_0/probe23]
  set_property HDL_ATTRIBUTE.DEBUG {true} [get_bd_nets HiCCEv2_v2022_0_Data_intan_B]
  connect_bd_net -net HiCCEv2_v2022_0_Data_intan_C [get_bd_pins CombIntan_w_header_0/DataIn_C] [get_bd_pins HiCCEv2_v2022_0/Data_intan_C] [get_bd_pins system_ila_0/probe24]
  set_property HDL_ATTRIBUTE.DEBUG {true} [get_bd_nets HiCCEv2_v2022_0_Data_intan_C]
  connect_bd_net -net HiCCEv2_v2022_0_Data_intan_D [get_bd_pins CombIntan_w_header_0/DataIn_D] [get_bd_pins HiCCEv2_v2022_0/Data_intan_D] [get_bd_pins system_ila_0/probe25]
  set_property HDL_ATTRIBUTE.DEBUG {true} [get_bd_nets HiCCEv2_v2022_0_Data_intan_D]
  connect_bd_net -net HiCCEv2_v2022_0_Data_valid [get_bd_pins CombIntan_w_header_0/DataIn_valid] [get_bd_pins HiCCEv2_v2022_0/Data_valid] [get_bd_pins counter64_0/clk] [get_bd_pins system_ila_0/probe26]
  set_property HDL_ATTRIBUTE.DEBUG {true} [get_bd_nets HiCCEv2_v2022_0_Data_valid]
  connect_bd_net -net HiCCEv2_v2022_0_Elec_Test [get_bd_ports Elec_Test_0] [get_bd_pins HiCCEv2_v2022_0/Elec_Test]
  connect_bd_net -net HiCCEv2_v2022_0_Elec_Test_en [get_bd_ports Elec_Test_en_0] [get_bd_pins HiCCEv2_v2022_0/Elec_Test_en]
  connect_bd_net -net HiCCEv2_v2022_0_LED_HiCCE_AB [get_bd_ports LED_HiCCE_AB_0] [get_bd_pins HiCCEv2_v2022_0/LED_HiCCE_AB]
  connect_bd_net -net HiCCEv2_v2022_0_Mode [get_bd_ports Mode_0] [get_bd_pins HiCCEv2_v2022_0/Mode] [get_bd_pins system_ila_0/probe27]
  set_property HDL_ATTRIBUTE.DEBUG {true} [get_bd_nets HiCCEv2_v2022_0_Mode]
  connect_bd_net -net HiCCEv2_v2022_0_Sel0_Reset [get_bd_ports Sel0_Reset_0] [get_bd_pins HiCCEv2_v2022_0/Sel0_Reset] [get_bd_pins system_ila_0/probe28]
  set_property HDL_ATTRIBUTE.DEBUG {true} [get_bd_nets HiCCEv2_v2022_0_Sel0_Reset]
  connect_bd_net -net HiCCEv2_v2022_0_Sel1_Step [get_bd_ports Sel1_Step_0] [get_bd_pins HiCCEv2_v2022_0/Sel1_Step] [get_bd_pins system_ila_0/probe29]
  set_property HDL_ATTRIBUTE.DEBUG {true} [get_bd_nets HiCCEv2_v2022_0_Sel1_Step]
  connect_bd_net -net HiCCEv2_v2022_0_Settle [get_bd_ports Settle_0] [get_bd_pins HiCCEv2_v2022_0/Settle]
  connect_bd_net -net Net [get_bd_ports Sel2_Sync_0] [get_bd_pins HiCCEv2_v2022_0/Sel2_Sync]
  connect_bd_net -net Net2 [get_bd_ports Sel3_0] [get_bd_pins HiCCEv2_v2022_0/Sel3]
  connect_bd_net -net Net3 [get_bd_ports Sel4_0] [get_bd_pins HiCCEv2_v2022_0/Sel4]
  connect_bd_net -net ab_tvalid_Res [get_bd_pins CombIntan_w_header_0/ab_maxis_tready] [get_bd_pins ab_tready/Res] [get_bd_pins system_ila_0/probe0]
  set_property HDL_ATTRIBUTE.DEBUG {true} [get_bd_nets ab_tvalid_Res]
  connect_bd_net -net cd_tready_Res [get_bd_pins CombIntan_w_header_0/cd_maxis_tready] [get_bd_pins cd_tready/Res] [get_bd_pins system_ila_0/probe2]
  set_property HDL_ATTRIBUTE.DEBUG {true} [get_bd_nets cd_tready_Res]
  connect_bd_net -net comblock_0_fifo_afull_o [get_bd_pins CombIntan_w_header_0/FIFO_AFULL_AB] [get_bd_pins comblock_0/fifo_afull_o] [get_bd_pins system_ila_0/probe7]
  set_property HDL_ATTRIBUTE.DEBUG {true} [get_bd_nets comblock_0_fifo_afull_o]
  connect_bd_net -net comblock_0_fifo_full_o [get_bd_pins ab_tready/Op1] [get_bd_pins comblock_0/fifo_full_o]
  connect_bd_net -net comblock_0_reg0_o [get_bd_pins HiCCEv2_v2022_0/Config_Res_intan_A] [get_bd_pins comblock_0/reg0_o]
  connect_bd_net -net comblock_0_reg1_o [get_bd_pins HiCCEv2_v2022_0/Config_Res_intan_B] [get_bd_pins comblock_0/reg1_o]
  connect_bd_net -net comblock_0_reg2_o [get_bd_pins HiCCEv2_v2022_0/Config_Res_intan_C] [get_bd_pins comblock_0/reg2_o]
  connect_bd_net -net comblock_0_reg3_o [get_bd_pins HiCCEv2_v2022_0/Config_Res_intan_D] [get_bd_pins comblock_0/reg3_o]
  connect_bd_net -net comblock_0_reg4_o [get_bd_pins HiCCEv2_v2022_0/FIFO_READ_ENB] [get_bd_pins HiCCEv2_v2022_0/Read_intan] [get_bd_pins comblock_0/reg4_o] [get_bd_pins system_ila_0/probe8]
  set_property HDL_ATTRIBUTE.DEBUG {true} [get_bd_nets comblock_0_reg4_o]
  connect_bd_net -net comblock_0_reg5_o [get_bd_pins comblock_0/reg5_o] [get_bd_pins util_vector_logic_0/Op2]
  connect_bd_net -net comblock_0_reg6_o [get_bd_pins CombIntan_w_header_0/nsasmples] [get_bd_pins comblock_0/reg6_o] [get_bd_pins system_ila_0/probe9]
  set_property HDL_ATTRIBUTE.DEBUG {true} [get_bd_nets comblock_0_reg6_o]
  connect_bd_net -net comblock_0_reg7_o [get_bd_pins CombIntan_w_header_0/sys_en] [get_bd_pins comblock_0/reg7_o] [get_bd_pins system_ila_0/probe10]
  set_property HDL_ATTRIBUTE.DEBUG {true} [get_bd_nets comblock_0_reg7_o]
  connect_bd_net -net comblock_1_fifo_afull_o [get_bd_pins CombIntan_w_header_0/FIFO_AFULL_CD] [get_bd_pins comblock_1/fifo_afull_o] [get_bd_pins system_ila_0/probe11]
  set_property HDL_ATTRIBUTE.DEBUG {true} [get_bd_nets comblock_1_fifo_afull_o]
  connect_bd_net -net comblock_1_fifo_full_o [get_bd_pins cd_tready/Op1] [get_bd_pins comblock_1/fifo_full_o]
  connect_bd_net -net counter64_0_q [get_bd_pins CombIntan_w_header_0/timestamp_i] [get_bd_pins counter64_0/q] [get_bd_pins system_ila_0/probe12]
  set_property HDL_ATTRIBUTE.DEBUG {true} [get_bd_nets counter64_0_q]
  connect_bd_net -net processing_system7_0_FCLK_CLK0 [get_bd_pins CombIntan_w_header_0/ab_maxis_clk] [get_bd_pins CombIntan_w_header_0/cd_maxis_clk] [get_bd_pins HiCCEv2_v2022_0/FIFO_clk] [get_bd_pins HiCCEv2_v2022_0/Sys_Clock] [get_bd_pins comblock_0/axil_aclk] [get_bd_pins comblock_0/fifo_clk_i] [get_bd_pins comblock_1/axil_aclk] [get_bd_pins comblock_1/fifo_clk_i] [get_bd_pins processing_system7_0/FCLK_CLK0] [get_bd_pins processing_system7_0/M_AXI_GP0_ACLK] [get_bd_pins ps7_0_axi_periph/ACLK] [get_bd_pins ps7_0_axi_periph/M00_ACLK] [get_bd_pins ps7_0_axi_periph/M01_ACLK] [get_bd_pins ps7_0_axi_periph/S00_ACLK] [get_bd_pins rst_ps7_0_100M/slowest_sync_clk] [get_bd_pins system_ila_0/clk]
  connect_bd_net -net processing_system7_0_FCLK_RESET0_N [get_bd_pins processing_system7_0/FCLK_RESET0_N] [get_bd_pins rst_ps7_0_100M/ext_reset_in]
  connect_bd_net -net rst_ps7_0_100M_peripheral_aresetn [get_bd_pins CombIntan_w_header_0/sys_rstn] [get_bd_pins comblock_0/axil_aresetn] [get_bd_pins comblock_1/axil_aresetn] [get_bd_pins counter64_0/rstn] [get_bd_pins ps7_0_axi_periph/ARESETN] [get_bd_pins ps7_0_axi_periph/M00_ARESETN] [get_bd_pins ps7_0_axi_periph/M01_ARESETN] [get_bd_pins ps7_0_axi_periph/S00_ARESETN] [get_bd_pins rst_ps7_0_100M/peripheral_aresetn] [get_bd_pins util_vector_logic_0/Op1]
  connect_bd_net -net util_vector_logic_0_Res [get_bd_pins HiCCEv2_v2022_0/Sys_Reset] [get_bd_pins system_ila_0/probe30] [get_bd_pins util_vector_logic_0/Res]
  set_property HDL_ATTRIBUTE.DEBUG {true} [get_bd_nets util_vector_logic_0_Res]
  connect_bd_net -net xlconstant_0_dout [get_bd_pins HiCCEv2_v2022_0/ADC_SDO_VIRTUAL_A] [get_bd_pins xlconstant_0/dout]

  # Create address segments
  assign_bd_address -offset 0x43C00000 -range 0x00010000 -target_address_space [get_bd_addr_spaces processing_system7_0/Data] [get_bd_addr_segs comblock_0/AXIL/AXIL] -force
  assign_bd_address -offset 0x43C10000 -range 0x00010000 -target_address_space [get_bd_addr_spaces processing_system7_0/Data] [get_bd_addr_segs comblock_1/AXIL/AXIL] -force

  # Perform GUI Layout
  regenerate_bd_layout -layout_string {
   "ActiveEmotionalView":"Default View",
   "Default View_ScaleFactor":"1.43587",
   "Default View_TopLeft":"-41,265",
   "ExpandedHierarchyInLayout":"",
   "guistr":"# # String gsaved with Nlview 7.0r4  2019-12-20 bk=1.5203 VDI=41 GEI=36 GUI=JA:10.0 TLS
#  -string -flagsOSRD
preplace port DDR -pg 1 -lvl 8 -x 3130 -y 970 -defaultsOSRD
preplace port FIXED_IO -pg 1 -lvl 8 -x 3130 -y 990 -defaultsOSRD
preplace portBus ADC_CNV_0 -pg 1 -lvl 8 -x 3130 -y 1190 -defaultsOSRD
preplace portBus ADC_SCLK_0 -pg 1 -lvl 8 -x 3130 -y 1210 -defaultsOSRD
preplace portBus Conn_All_0 -pg 1 -lvl 8 -x 3130 -y 1270 -defaultsOSRD
preplace portBus Elec_Test_0 -pg 1 -lvl 8 -x 3130 -y 1230 -defaultsOSRD
preplace portBus Elec_Test_en_0 -pg 1 -lvl 8 -x 3130 -y 1250 -defaultsOSRD
preplace portBus LED_HiCCE_AB_0 -pg 1 -lvl 8 -x 3130 -y 1170 -defaultsOSRD
preplace portBus Mode_0 -pg 1 -lvl 8 -x 3130 -y 1410 -defaultsOSRD
preplace portBus Sel0_Reset_0 -pg 1 -lvl 8 -x 3130 -y 1310 -defaultsOSRD
preplace portBus Sel1_Step_0 -pg 1 -lvl 8 -x 3130 -y 1330 -defaultsOSRD
preplace portBus Sel3_0 -pg 1 -lvl 8 -x 3130 -y 1370 -defaultsOSRD
preplace portBus Sel4_0 -pg 1 -lvl 8 -x 3130 -y 1390 -defaultsOSRD
preplace portBus Settle_0 -pg 1 -lvl 8 -x 3130 -y 1290 -defaultsOSRD
preplace portBus Sel2_Sync_0 -pg 1 -lvl 8 -x 3130 -y 1350 -defaultsOSRD
preplace portBus ADC_SDO_0 -pg 1 -lvl 0 -x -10 -y 1200 -defaultsOSRD
preplace inst HiCCEv2_v2022_0 -pg 1 -lvl 6 -x 2560 -y 1280 -defaultsOSRD
preplace inst processing_system7_0 -pg 1 -lvl 2 -x 620 -y 1050 -defaultsOSRD
preplace inst rst_ps7_0_100M -pg 1 -lvl 1 -x 220 -y 1300 -defaultsOSRD
preplace inst counter64_0 -pg 1 -lvl 2 -x 620 -y 860 -defaultsOSRD
preplace inst xlconstant_0 -pg 1 -lvl 5 -x 2120 -y 1360 -defaultsOSRD
preplace inst comblock_0 -pg 1 -lvl 4 -x 1720 -y 800 -defaultsOSRD
preplace inst comblock_1 -pg 1 -lvl 4 -x 1720 -y 200 -defaultsOSRD
preplace inst util_vector_logic_0 -pg 1 -lvl 5 -x 2120 -y 1060 -defaultsOSRD
preplace inst ps7_0_axi_periph -pg 1 -lvl 3 -x 1130 -y 830 -defaultsOSRD
preplace inst ab_tready -pg 1 -lvl 5 -x 2120 -y 670 -defaultsOSRD
preplace inst cd_tready -pg 1 -lvl 5 -x 2120 -y 80 -defaultsOSRD
preplace inst system_ila_0 -pg 1 -lvl 7 -x 3010 -y 520 -defaultsOSRD
preplace inst CombIntan_w_header_0 -pg 1 -lvl 3 -x 1130 -y 430 -defaultsOSRD
preplace netloc ADC_SDO_0_1 1 0 7 NJ 1200 NJ 1200 NJ 1200 NJ 1200 NJ 1200 2310 250 NJ
preplace netloc CLK_SWITCH_INT_A 1 6 1 N 1430
preplace netloc CLK_SWITCH_INT_B 1 6 1 N 1450
preplace netloc CLK_SWITCH_INT_C 1 6 1 N 1470
preplace netloc CLK_SWITCH_INT_D 1 6 1 N 1490
preplace netloc CombIntan_w_header_0_FIFO_CLEAR_AB 1 3 1 1320 450n
preplace netloc CombIntan_w_header_0_FIFO_CLEAR_CD 1 3 1 1380 260n
preplace netloc CombIntan_w_header_0_ab_maxis_tdata 1 3 4 1400 370 1900J 310 2290J 290 NJ
preplace netloc CombIntan_w_header_0_ab_maxis_tvalid 1 3 4 1390 380 1920J 320 NJ 320 2780J
preplace netloc CombIntan_w_header_0_cd_maxis_tdata 1 3 4 1360 30 1960J 330 NJ 330 N
preplace netloc CombIntan_w_header_0_cd_maxis_tvalid 1 3 4 1350 10 NJ 10 NJ 10 2850
preplace netloc DBG_COUNT_AB 1 3 4 NJ 490 NJ 490 NJ 490 N
preplace netloc DBG_COUNT_CD 1 3 4 1430J 510 NJ 510 NJ 510 N
preplace netloc DBG_MAX_COUNT_AB 1 3 4 1330J 520 NJ 520 NJ 520 2850
preplace netloc DBG_MAX_COUNT_CD 1 3 4 NJ 550 NJ 550 NJ 550 N
preplace netloc DBG_STATE_AB 1 3 4 NJ 570 NJ 570 NJ 570 N
preplace netloc DBG_STATE_CD 1 3 4 NJ 590 NJ 590 NJ 590 N
preplace netloc HiCCEv2_v2022_0_ADC_CNV 1 6 2 2810 1190 NJ
preplace netloc HiCCEv2_v2022_0_ADC_SCLK 1 6 2 2820 1210 NJ
preplace netloc HiCCEv2_v2022_0_Ack_intan 1 2 5 890 200 1480J 400 NJ 400 NJ 400 2780
preplace netloc HiCCEv2_v2022_0_Conn_All 1 6 2 NJ 1270 NJ
preplace netloc HiCCEv2_v2022_0_Data_intan_A 1 2 5 860 160 1340J 440 NJ 440 NJ 440 2770
preplace netloc HiCCEv2_v2022_0_Data_intan_B 1 2 5 860 650 1450J 600 NJ 600 NJ 600 2760
preplace netloc HiCCEv2_v2022_0_Data_intan_C 1 2 5 870 660 1470J 610 NJ 610 NJ 610 2750
preplace netloc HiCCEv2_v2022_0_Data_intan_D 1 2 5 880 670 1490J 640 1900J 730 NJ 730 2800
preplace netloc HiCCEv2_v2022_0_Data_valid 1 1 6 400 680 840 680 1480J 620 1910J 750 NJ 750 2790
preplace netloc HiCCEv2_v2022_0_Elec_Test 1 6 2 NJ 1230 NJ
preplace netloc HiCCEv2_v2022_0_Elec_Test_en 1 6 2 NJ 1250 NJ
preplace netloc HiCCEv2_v2022_0_LED_HiCCE_AB 1 6 2 NJ 1170 NJ
preplace netloc HiCCEv2_v2022_0_Mode 1 6 2 2840 1410 NJ
preplace netloc HiCCEv2_v2022_0_Sel0_Reset 1 6 2 2830 1310 NJ
preplace netloc HiCCEv2_v2022_0_Sel1_Step 1 6 2 2850 1330 NJ
preplace netloc HiCCEv2_v2022_0_Settle 1 6 2 NJ 1290 NJ
preplace netloc Net 1 6 2 NJ 1350 NJ
preplace netloc Net2 1 6 2 NJ 1370 NJ
preplace netloc Net3 1 6 2 NJ 1390 NJ
preplace netloc ab_tvalid_Res 1 3 4 1460J 360 NJ 360 2280 230 NJ
preplace netloc cd_tready_Res 1 3 4 NJ 410 1910J 300 2270 270 NJ
preplace netloc comblock_0_fifo_afull_o 1 2 5 900 210 1410 390 1960J 380 NJ 380 2780
preplace netloc comblock_0_fifo_full_o 1 3 2 1500 630 1930J
preplace netloc comblock_0_reg0_o 1 4 2 NJ 740 2300
preplace netloc comblock_0_reg1_o 1 4 2 NJ 760 2290
preplace netloc comblock_0_reg2_o 1 4 2 NJ 780 2280
preplace netloc comblock_0_reg3_o 1 4 2 NJ 800 2270
preplace netloc comblock_0_reg4_o 1 4 3 NJ 820 2320 390 NJ
preplace netloc comblock_0_reg5_o 1 4 1 1900 840n
preplace netloc comblock_0_reg6_o 1 2 5 880 170 1490J 420 1920 410 NJ 410 NJ
preplace netloc comblock_0_reg7_o 1 2 5 870 20 NJ 20 1940 420 NJ 420 2850J
preplace netloc comblock_1_fifo_afull_o 1 2 5 850 180 1330 450 NJ 450 NJ 450 N
preplace netloc comblock_1_fifo_full_o 1 3 2 1500 40 1950J
preplace netloc counter64_0_q 1 2 5 830 690 1460J 470 NJ 470 NJ 470 NJ
preplace netloc processing_system7_0_FCLK_CLK0 1 0 7 30 1050 390 790 810 190 1420 430 NJ 430 2330 210 NJ
preplace netloc processing_system7_0_FCLK_RESET0_N 1 0 3 40 1190 NJ 1190 810
preplace netloc rst_ps7_0_100M_peripheral_aresetn 1 1 4 400 1210 820 150 1440 1050 NJ
preplace netloc util_vector_logic_0_Res 1 5 2 2340 830 NJ
preplace netloc xlconstant_0_dout 1 5 1 NJ 1360
preplace netloc processing_system7_0_DDR 1 2 6 NJ 970 NJ 970 NJ 970 NJ 970 NJ 970 NJ
preplace netloc processing_system7_0_FIXED_IO 1 2 6 NJ 990 NJ 990 NJ 990 NJ 990 NJ 990 NJ
preplace netloc processing_system7_0_M_AXI_GP0 1 2 1 870 750n
preplace netloc ps7_0_axi_periph_M00_AXI 1 3 1 1380 700n
preplace netloc ps7_0_axi_periph_M01_AXI 1 3 1 1370 100n
levelinfo -pg 1 -10 220 620 1130 1720 2120 2560 3010 3130
pagesize -pg 1 -db -bbox -sgen -160 0 3320 1570
"
}

  # Restore current instance
  current_bd_instance $oldCurInst

  validate_bd_design
  save_bd_design
  close_bd_design $design_name 
}
# End of cr_bd_HICCEv2_w_header()
cr_bd_HICCEv2_w_header ""
set_property GENERATE_SYNTH_CHECKPOINT "0" [get_files HICCEv2_w_header.bd ] 
set_property REGISTERED_WITH_MANAGER "1" [get_files HICCEv2_w_header.bd ] 

set idrFlowPropertiesConstraints ""
catch {
 set idrFlowPropertiesConstraints [get_param runs.disableIDRFlowPropertyConstraints]
 set_param runs.disableIDRFlowPropertyConstraints 1
}

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xc7z020clg484-1 -flow {Vivado Synthesis 2022} -strategy "Flow_AreaOptimized_medium" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Flow_AreaOptimized_medium" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2022" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_1]
set_property -name "incremental_checkpoint" -value "$proj_dir/hicce_w_header.srcs/utils_1/imports/synth_1/HICCEv2_w_header_wrapper.dcp" -objects $obj
set_property -name "auto_incremental_checkpoint" -value "1" -objects $obj
set_property -name "strategy" -value "Flow_AreaOptimized_medium" -objects $obj
set_property -name "steps.synth_design.args.directive" -value "AreaOptimized_medium" -objects $obj
set_property -name "steps.synth_design.args.control_set_opt_threshold" -value "1" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xc7z020clg484-1 -flow {Vivado Implementation 2022} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2022" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {
set_property -name "options.verbose" -value "1" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
set obj [get_runs impl_1]
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]
catch {
 if { $idrFlowPropertiesConstraints != {} } {
   set_param runs.disableIDRFlowPropertyConstraints $idrFlowPropertiesConstraints
 }
}

puts "INFO: Project created:${_xil_proj_name_}"
# Create 'drc_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "drc_1" ] ] ""]} {
create_dashboard_gadget -name {drc_1} -type drc
}
set obj [get_dashboard_gadgets [ list "drc_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_drc_0" -objects $obj

# Create 'methodology_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "methodology_1" ] ] ""]} {
create_dashboard_gadget -name {methodology_1} -type methodology
}
set obj [get_dashboard_gadgets [ list "methodology_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_methodology_0" -objects $obj

# Create 'power_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "power_1" ] ] ""]} {
create_dashboard_gadget -name {power_1} -type power
}
set obj [get_dashboard_gadgets [ list "power_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_power_0" -objects $obj

# Create 'timing_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "timing_1" ] ] ""]} {
create_dashboard_gadget -name {timing_1} -type timing
}
set obj [get_dashboard_gadgets [ list "timing_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_timing_summary_0" -objects $obj

# Create 'utilization_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_1" ] ] ""]} {
create_dashboard_gadget -name {utilization_1} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_1" ] ]
set_property -name "reports" -value "synth_1#synth_1_synth_report_utilization_0" -objects $obj
set_property -name "run.step" -value "synth_design" -objects $obj
set_property -name "run.type" -value "synthesis" -objects $obj

# Create 'utilization_2' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_2" ] ] ""]} {
create_dashboard_gadget -name {utilization_2} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_2" ] ]
set_property -name "reports" -value "impl_1#impl_1_place_report_utilization_0" -objects $obj

move_dashboard_gadget -name {utilization_1} -row 0 -col 0
move_dashboard_gadget -name {power_1} -row 1 -col 0
move_dashboard_gadget -name {drc_1} -row 2 -col 0
move_dashboard_gadget -name {timing_1} -row 0 -col 1
move_dashboard_gadget -name {utilization_2} -row 1 -col 1
move_dashboard_gadget -name {methodology_1} -row 2 -col 1
